### ISSUE TITLE
Configurable inclusion of SAD request

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/signservice#150]
The inclusion of a SAD request is currently not configurable, but rather controlled by the status of the IdP and the sign request.

The following parts of the code is involved:

`DefaultSignServiceEngine` has a //TODO at row 513 stating:
```
      // Note: The authentication requirements may also be controlled by a policy ...
      // TODO: We need to extend the input to authenticate with a listing of all attributes
      // required. We get those from the signing certificate requirements ...
      final AuthnRequirements reqs = signRequest.getAuthnRequirements();
```

This is a place where it could be possible to influence the authentication requirements. `AuthenticationRequirements` has a parameter of type `SignatureActivationRequestData`. If set to null, it will not send a SAD request.

The `SignatureActivationRequestData` is set by parsing the `SignRequest` in row 536 of `DssSignRequestMessage`

```
    authnRequirements.setSignatureActivationRequestData(
        new DefaultSignatureActivationRequestData(
            this.signRequest.getRequestID(), docCount, certType == CertificateType.QC_SSCD));

```

Using this code, it will never be null.

Finally the decision to include SAD request is mad by `SwedenConnectSamlAuthenticationHandler` at row 126

```
    // Should we send a SAD request?
    //
    final SADRequest sadRequest = authnRequirements.getSignatureActivationRequestData() != null
        && signMessage != null
        && this.isSignatureActivationProtocolSupported(idpMetadata)
            ? (SADRequest) XMLObjectSupport.buildXMLObject(SADRequest.DEFAULT_ELEMENT_NAME)
            : null;
    if (sadRequest != null) {
```

I think this is the appropriate place to have a configurable option to not send a SAD request.

Given that the `SignatureActivationRequestData` is never null. The current logic is:

If signMessage is present and IdP supports SAD, then send SAD request.

This should be replaced by the following logic:

boolean SADREQ_ALWAYS_IF_SUPPORTED = true;
boolean sendSad = false;

1. If qualified certificate is requested: sendSad = true
2. If IdP supports SAD && SADREQ_ALWAYS_IF_SUPPORTED: sendSad = true
3. If IdP does not support SAD && sendSad: Error
4. if (sendSad) send SAD request

**Comment by martin-lindstrom** [comment]
Fixed in PR https://github.com/swedenconnect/signservice/pull/152
