### ISSUE TITLE
javax vs jakarta issue, using the application bom in Java EE 9/10 based app (quarkus 3)

### ISSUE THREAD

**Issue by janderssonse** [swedenconnect/signservice#159]
**Background:**
A lot of frameworks Spring/Quarkus etc has been releasing major new versions with a breaking change to the Java Eco-system. javax->jakarta.  Quarkus 2.x is now on it's way out, and Quarkus 3.x is where most bugfixes go, ( and the recommended version ). For us, when currently using the signservie-application-bom, further down the dependency chain, the xml utils is used. https://github.com/idsec-solutions/signservice-commons/tree/master/commons/signservice-commons/src/main/java/se/idsec/signservice/xml, and with that comes javax. usage during runtime.  

**Our problems:** 
We have been testing the Quarkus 3.x releases but they are missing the javax. packages, during runtime (as intented by Quarkus 3x). Coexistence with javax is not an straightforward option either as Quarkus wont include all javax. libraries in the jar dependencies build results as they are changed to jakarta.
While, we could most likely hack around it a bit on our side , (bypass the filtering of deps on the quarkus side, add the missing jars to the build results and see if the classloader picks them up etc), it feels to hackish for us.

**Solution proposal:**
Is it possible to use the jakarta versions of the libs in the util artifacts, replacing javax?

**Comment by martin-lindstrom** [comment]
See #162

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/signservice/pull/163
