### ISSUE TITLE
Failfast as a config property

### ISSUE THREAD

**Issue by janderssonse** [swedenconnect/signservice#160]
We would like to be able to set the failfast-property of the metadataprovider. Currently it is a bit buried, due to the provider being both created and intialized inside the create() method https://github.com/swedenconnect/signservice/blob/f5d49e265c52bd46c109d5d45f9ea5dcc3c90da7/authn/saml/src/main/java/se/swedenconnect/signservice/authn/saml/config/MetadataProviderConfiguration.java

A suggestion that would save us from implementing and overriding quite a few code snippets would be to make the property externally available as a config-boolean. Suggestion before the initialization method of the provider, example: provider.setFailFastInitialization(The-Boolean-from-config>);

**Comment by martin-lindstrom** [comment]
@janderssonse Will fix this in 1.1.0 (i.e., Java 17 version). OK?

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/signservice/pull/164
