### ISSUE TITLE
Sign service provides error UI even when the user cold be returned to the requesting service

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/signservice#64]
A fundamental requirement for sign services has always been the principle that the Sign Service has no UI for the user unless the request can't be returned to the requesting service for one of the following reasons:

- The real requestor can't be safely identified
- The return address to the requesting service is unknown 
- The request is a replay attempt
- The request is not received within its validity period.

In all other instances, the user MUST be returned to the requesting service with an appropriate status indication in order to allow that application to get the user back and to handle the user in an appropriate manner.

Sign service currently does not meet this requirement. One case is there a request is made for an unsupported certificate type (QC, PKC, QC/SSSCD). If the requested certificate type is not supported, the user is presented by an error page claiming "internal error". In this case the user should be returned to the requesting service with an appropriate error response.

**Comment by martin-lindstrom** [comment]
@Razumain Internal error clearly states that something bad went wrong in the checks. Please investigate the checks made in checkRequirements of the KeyAndCert handler and make sure that InvalidRequest is thrown (which will be translated into an error response message being sent back).

**Comment by martin-lindstrom** [comment]
There is a bug in the method of sending back an error message. Will fix this.

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/signservice/pull/66.
