### ISSUE TITLE
Order of checks - Signature validation before simpler validity checks

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/signservice#81]
Signature validation is performed before simpler checks such as checks if the request is too old to be processed.

It is a good principle to do easier and less costly checks first, such as simple date checks before doing costly checks such as signature validation in order to reduce the attack surface for DOS attacks.

**Comment by martin-lindstrom** [comment]
I don't agree. Until we have verified the signature we can't trust anything in the request. And it isn't very hard for a DOS-attacker to construct a request message that has correct timestamps anyway.

**Comment by martin-lindstrom** [comment]
The thing is that the only thing that can prevent us from a request sent be someone not authorized is to check the signature. Everything else can be forged, so it is actually more efficient to check the signature first.

**Comment by Razumain** [comment]
You are right in principle. However, you can still prevent some dumb attacks by doing some basic cheep checks. I still think it is good practice to have this order:

- Check syntax (can I parse this as a message relevant for my service)
- Is it adressed to me
- Check against replay
- Check signature
- Check rest

Even if the signature check is necessary to trust any information, signature check is wasted if the checks above it fails.

Checking time is part of a replay check. The reason is that the replay cache only holds information about recent messages. If you can present an old document to the replay checker, then the replay checker may pass it as original unless it checks the time code.

**Comment by Razumain** [comment]
However, there is one argument that may tip the scale in favour of your conclusion.

Any checks based on unvalidated signed data, must be repeated after signature check in order to prevent signature wrapping attacks (i.e. a valid signed document is wrapped in a false unsigned document). You don't know for sure what data that is covered by the signature util you have checked the signature. That includes time information.

**Comment by martin-lindstrom** [comment]
@Razumain OK, so we won't change anything. Does this mean that we have to modify any tests?
