### ISSUE TITLE
Too long request validity is ignored

### ISSUE THREAD

**Issue by Razumain** [swedenconnect/signservice#84]
If a Sign Request has a validity period that is too long (i.e. 1 hour), the sign request is processed as long as current time is within the validity period.

The risk here is that the validity period exceeds the replay checker retention period and opens for successful replay attacks.

**Comment by martin-lindstrom** [comment]
Yes. We do have settings for this. I will investigate why they don't trigger.

**Comment by martin-lindstrom** [comment]
See https://github.com/swedenconnect/technical-framework/issues/190

The test that triggered this issue is not correct. Should be fixed.
